### ISSUE TITLE
[Enhancement] Metadata Utilities: Age Ratings

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extensions#109]
**Is your feature request related to a problem? Please describe.**
I would like to automatically discard any ratings other than ESRB and PEGI.

**Describe the solution you'd like**
Support in Metadata Utilities for modifying age ratings.

**Comment by HerrKnarz** [comment]
Age ratings are now implemented. I'm not sure when the next version will be ready, yet, because I want to add some more features to it.
