### ISSUE TITLE
[Enhancement] [Metadata Utilities] Include time played as criteria for conditional actions

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extensions#115]
**Is your feature request related to a problem? Please describe.**
A specific limitation in Playnite is that _only_ the 'default status assigned to newly added games' will automatically update upon the first play. This would help with a workaround.

**Describe the solution you'd like**
Add 'time played' as a possible criteria for conditional actions, with 'is/is not empty' and 'bigger/smaller than,' as options. i'm not sure how useful contains/doesn't is. 

**Additional context**
I'd like to make a conditional action where if the completion status is 'Want to Play' and playtime is greater than 3600 seconds (an hour), it automatically changes to 'played.'

**Comment by HerrKnarz** [comment]
That's already possible in the latest beta version I posted on discord yesterday!
