### ISSUE TITLE
[Enhancement] [Link Utilities] Custom search URLs, opened in browser

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extensions#41]
**Is your feature request related to a problem? Please describe.**
Mostly the inability to add IGDB links directly. This would somewhat improve the workflow of adding via bookmarklet.

**Describe the solution you'd like**

The option to add custom search query URLs based on [GameMetadata.](https://playnite.link/docs/api/Playnite.SDK.Models.GameMetadata.html), which would then open in browser. At the very least, the game title, but I can think of usecases where developer/publisher would be helpful.

Example:
IGDB link, create a custom search URL `https://www.igdb.com/search?type=1&q={Name}`
Run it on a game called "Hero of the Kingdom" would produce `https://www.igdb.com/search?type=1&q=hero+of+the+kingdom`
Then I would select the correct game from the search results opened in browser and use the bookmarklet.

Thanks in advance

**Comment by chocolatechipcats** [comment]
I got the idea from the settings of the Vivaldi browser, which allow adding custom search engines.

![image](https://user-images.githubusercontent.com/47759676/224487223-91703b9b-0a5a-4635-a79a-1bdb26df5105.png)

**Comment by HerrKnarz** [comment]
For that purpose there's already the addon "[Search Collection](https://github.com/darklinkpower/PlayniteExtensionsCollection/wiki/Search-Collection)" by darklinkpower. It only supports the game name yet, but I think it would be better to open an issue for darklinkpower to add more fields to their addon.

**Comment by chocolatechipcats** [comment]
Thank you!
