### ISSUE TITLE
[Enhancement] Link Utilities: Add link from clipboard

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extensions#49]
**Describe the solution you'd like**
Alternative to the bookmarklet: "Add link from clipboard" in the Link Utilities menu. If possible, fetch the name from the website, or just use the domain if that's complicated. Run the renaming and sorting rules on it afterwards.

**Comment by HerrKnarz** [comment]
Added in version 3.1

Instead of fetching the name from the website, which would yield incoherent results, the same link name patterns that find a name for bookmarklet links will be used (only the url pattern in this case).
