### ISSUE TITLE
[Enhancement] Link Utilities: Remove [Missing Link] tags when link added

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extensions#55]
**Is your feature request related to a problem? Please describe.**
If a user runs 'Tag Missing Links' and then uses bookmarklet/paste from clipboard (or possibly add link; have not tested) to add the links, they then have to take an extra step of opening the game details to delete the tag. 

**Describe the solution you'd like**
When adding a link from bookmarklet or clipboard (or 'add link' if it's affected), the extension should check for matching 'missing link' rules. If there are any, remove the tag from the game.

**Describe alternatives you've considered**
Simply deleting the tag in Library Manager afterwards kind of works, but it makes it harder when adding links in multiple batches.

**Additional context**
n/a

**Comment by HerrKnarz** [comment]
That's strange! It should already do that. I'll look into it!

**Comment by chocolatechipcats** [comment]
For replication:

Name Pattern is IGDB and URL Pattern is `https://www.igdb.com/*`

**Comment by HerrKnarz** [comment]
I just had the chance to test it and it works for me. But there is a known bug, that the tags aren't refreshed in the detail view after the action, but they actually have changed in the background. When you switch to another game and back you should see the change and the Missing-link-tag should be gone. Can you please check if that works for you, too?

Unfortunately it seems I can't do much about that. It seems to be a bug in Playnite itself. I added a new FAQ page to the wiki for that bug.

**Comment by chocolatechipcats** [comment]
I think figured out the issue: I had the 'tag missing links on metadata update' option turned off so it wouldn't keep re-tagging the rare game that _isn't_ on IGDB.
