### ISSUE TITLE
[Enhancement] Link Utilities: Check dead links & resolve redirects

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extensions#56]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
'Check Links' option. 

If the HTTP status indicates an error, notify the user with an option to open the link and check. 
Give options to delete the link, exclude from future checks (for fussy websites like CurseForge), or do nothing (for transient errors). 
If the link is a 301, offer to change the link.

To prevent hammering websites, it would probably be best if this was not available library-span. 

Perhaps also give an option to exclude certain domains. (CurseForge is one that should be included by default as they heavily block access.)

**Describe alternatives you've considered**
n/a

**Additional context**
Use-case: When download links for new game, I got two different 'official website' links, for https://www.starcontrol.com and https://www.stardock.com/games/starcontrol/ -- the former just redirected to the latter.

**Comment by chocolatechipcats** [comment]
yes, the CurseForge thing made me think of that. Perhaps this could be pushed back in scope to just handle 301s like the one I mentioned.

**Comment by HerrKnarz** [comment]
I added the functionality now. It will be in the next release!
