### ISSUE TITLE
[Bug]Blank entry in "remove links" option menu will result in all links being removed when using "remove unwanted links"

### ISSUE THREAD

**Issue by OldFinbar** [HerrKnarz/Playnite-Extensions#67]
**Describe the bug**
If a blank entry is added in the options menu on the "remove links" page, when you choose the "remove unwanted links" option from the right click menu, all links from the selected game/s will be removed.

**To Reproduce**
1. Go to Link Utilities extension settings
2. On 'Remove links' page add a new line but leave all fields blank and save.
3. Go back to your Playnite library and right click on a game (or select multiple games).
4. Click 'Link utilities' > 'Remove all unwanted links'
5. Watch as all links for the selected entries are removed

**Expected behavior**
I believe if a blank entry is added on the 'Remove links' option page, this should have no effect on your links when selecting 'remove all unwanted links'. It is very easy to quickly wipe out an entire library worth of links with the current behaviour. 

**Screenshots**
![blank entry](https://github.com/HerrKnarz/Playnite-Extensions/assets/72481617/060baaf6-d558-4b39-922d-79125ae54b59)

**please complete the following information:**
 - Windows version: Windows 10
 - Playnite version: 10.18
 - Extension version: 3.4

**Comment by HerrKnarz** [comment]
A new release with a fix for the bug will be released in the next few days. It's already fixed in the repository.
