### ISSUE TITLE
[Bug] Quick Add settings not showing up.

### ISSUE THREAD

**Issue by Gagaro** [HerrKnarz/Playnite-Extensions#77]
**Describe the bug**
I just installed Quick Add and rebooted Playnite but the settings are not showing up. Maybe am I just not looking at the right place? But I can't find them anywhere.

Thanks

**To Reproduce**
Install Quick Add and reboot Playnite.

**Expected behavior**
Being able to change the settings.

**Screenshots**
![image](https://github.com/HerrKnarz/Playnite-Extensions/assets/3845486/05a7fdd2-8a05-41c5-b5ba-307bd39186b2)
![image](https://github.com/HerrKnarz/Playnite-Extensions/assets/3845486/279e6b83-bb49-4294-9170-b5c9c6830f7b)

**please complete the following information:**
 - Windows version: 10
 - Playnite version: 10.20
 - Extension version: 0.3

**Comment by HerrKnarz** [comment]
Sorry for replying so late. Out of the box the add-on doesn't add menu entries. You first have to select the tags, features or categories you want to show up in the menus in the add-on settings page. Those will then appear in the context menu for each game, not in the Extensions menu directly. I added a short tutorial on how to use the add-on to the wiki now: https://github.com/HerrKnarz/Playnite-Extensions/wiki/Quick-Add-quick-start-guide
