### ISSUE TITLE
[Enhancement] Metadata Utilities: Filter to duplicate items

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extensions#83]
**Describe the solution you'd like**
In Metadata Utilities, it would be useful to be able to filter to items that are duplicated across different metadata types. For example, genre and feature both "Early Access." This would make it easier to find them for merging.

**Describe alternatives you've considered**
Sorting by name works, though it's easy to miss entries.

**Comment by HerrKnarz** [comment]
That's already planned - even a bit more sophisticated similar to Company Companion.

**Comment by HerrKnarz** [comment]
Added the functionality to v0.5
