### ISSUE TITLE
[Enhancement][Metadata Utilities] Add items when (combination of?) other values exist

### ISSUE THREAD

**Issue by Jeshibu** [HerrKnarz/Playnite-Extensions#87]
Consider you've got the tags `First-person shooter` and `Third-person shooter`, and you want those to automatically add the genre `Shooter` to a game.

Another use case for combined requirements: you've got genres `Perspective: Third Person` and `Shooter` and you want that to add the genre `Third-person shooter`

**Comment by HerrKnarz** [comment]
I thought about how to implement that. Here's a rough idea:

- support three condition types:
    - All conditions are met
    - None of the conditions are met
    - At least one of the conditions is met
- a rule can have any number of conditions. A condition can be the following:
     - field xy = abc (also support fields like library here)
     - field xy is empty
     - field xy != abc
- a rule can have any number of actions to take. An action can be the following:
    - add value ABC to field XY
    - remove value ABC from field XY

**Comment by HerrKnarz** [comment]
Added in the next release!
