### ISSUE TITLE
[Enhancement][Metadata Utilities] Option to add "metadata sets" - list of values for different fields to set at once.

### ISSUE THREAD

**Issue by HerrKnarz** [HerrKnarz/Playnite-Extensions#96]
This could be useful for different kinds of games. For example emulated console games could be set to a metadata set called "couch gaming", that automatically adds the feature "controller support" and tag "Couch gaming". Can be implemented as manual entries in the game context menu, but maybe later also tied to rules like "every game from plaform x will be set to metadata set abc" (see #87).

It also should be possible to set items to "remove" instead of "add" in this case, so stuff like "remove all steam features" is possible.

**Comment by chocolatechipcats** [comment]
Additional feedback: An additional option that might be useful here is "clear field entirely." 

My specific use-case: I like to have only one category per game. When adding a new category, it means adding the new category while also removing the old one. While adding all existing categories to the "remove" options would work here, simply clearing it entirely would be more useful.

**Comment by HerrKnarz** [comment]
Good idea, but I'm not sure how to implement that elegantly. I could add an option to each set to either replace existing metadata with the new set or simply add the new ones. But that wouldn't be very flexible, since the sets won't be restricted to only one type of metadata and you wouldn't want to replace them all, I guess. It will need to be toggleable for each type separately, but that probably will be a bit ugly UI wise.

**Comment by HerrKnarz** [comment]
I combined this feature with the condition based one #87, because both are very similar, only that this one is fired manually. I'll shelve this one and add the other probably as the next big feature after version 1.0

**Comment by HerrKnarz** [comment]
duplicate of #87

**Comment by HerrKnarz** [comment]
Duplicate of #87

**Comment by HerrKnarz** [comment]
Closed with the next version!
